// Each project gets its own detail page at /projects/<id>.
// Image tags: big | medium | small | video. `isRight` floats a small image right.
const projects = [
  {
    id: 'linklytics',
    title: 'Linklytics — URL Shortener & Analytics',
    img: '/projects/linklytics/cover.png',
    link: '/projects/linklytics',
    date: 'May 2025',
    liveLink: "https://url-shortner-frontend-abhay.netlify.app/",
    company: 'Full Stack Personal Project',
    primary: '#2D2D2D',
    accentColor: '#f0f4f1',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: '#c8b273',
    menuFontColor: '#f0f4f1',
    images: [
      { src: '/projects/linklytics/1.png', tag: 'big', isRight: false },
      { src: '/projects/linklytics/2.png', tag: 'small', isRight: false },
      { src: '/projects/linklytics/3.png', tag: 'small', isRight: true },
      { src: '/projects/linklytics/4.png', tag: 'big', isRight: false },
    ],
    desc: [
      'Linklytics is a high-performance URL shortening and management platform designed to deliver instant link redirection and detailed real-time click tracking.',
      'Architected a full-stack system powered by a Spring Boot REST API with Spring Security and JWT authentication, backed by PostgreSQL on Neon DB. The frontend is built using React, Vite, Tailwind CSS, and Chart.js for data visualization.',
      'Engineered core features including sub-second redirect handling, secure multi-tenant user dashboards, one-click clipboard copying, and analytics metrics for total clicks and link performance.',
    ],
  },
  {
    id: 'resumind',
    title: 'Resumind — AI ATS Resume Analyzer',
    img: '/projects/resumind/cover.png',
    link: '/projects/resumind',
    date: 'March 2025',
    liveLink: "https://ai-resume-analyzer-main.vercel.app/",
    company: 'Full Stack AI based Personal Project',
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    images: [
      { src: '/projects/resumind/1.png', tag: 'big', isRight: false },
      { src: '/projects/resumind/2.png', tag: 'small', isRight: false },
      { src: '/projects/resumind/3.png', tag: 'small', isRight: true },
      { src: '/projects/resumind/4.png', tag: 'big', isRight: false },
    ],
    desc: [
      'Job seekers frequently struggle with automated Applicant Tracking Systems (ATS) filtering out qualified resumes due to formatting inconsistencies, tone, and keyword mismatches.',
      'Developed an AI-driven resume optimization platform using React 19, TypeScript, React Router 7, and TailwindCSS 4, powered by Claude 3.7 Sonnet and Puter.js for cloud authentication and storage.',
      'Engineered client-side PDF parsing and rendering with PDF.js, dynamic score gauges for ATS compatibility, job-specific keyword matching, and version-tracking dashboards for iterative resume refinement.',
    ],
  },
  {
    id: 'election-analysis-2024',
    title: '2024 Indian Election Analysis Dashboard',
    img: '/projects/election-analysis-2024/cover.png',
    link: '/projects/election-analysis-2024',
    date: 'May 2025',
    liveLink: "https://app.powerbi.com/view?r=eyJrIjoiZWY1ZWQwYmEtY2UxMi00OWUxLTlhOGEtMWExMWI3Y2ZhZDQ2IiwidCI6ImIyZTljYjQyLTUxMTktNDUxYi05NzI5LWYyNGE1NzEzNjk3MyJ9",
    company: 'Data Analytics & BI Project',
    primary: '#1f3a34',
    accentColor: '#f0f4f1',
    secondary: '#F4F7F5',
    fillColor: '#e1f2ea',
    menuColor: '#2f8a6a',
    menuFontColor: '#f0f4f1',
    images: [
      { src: '/projects/election-analysis-2024/1.png', tag: 'big', isRight: false },
      { src: '/projects/election-analysis-2024/2.png', tag: 'small', isRight: false },
      { src: '/projects/election-analysis-2024/3.png', tag: 'small', isRight: true },
      { src: '/projects/election-analysis-2024/4.png', tag: 'big', isRight: false },
      { src: '/projects/election-analysis-2024/5.png', tag: 'medium', isRight: false },
      { src: '/projects/election-analysis-2024/6.png', tag: 'medium', isRight: false },
    ],
    desc: [
      'The 2024 Indian General Elections generated massive, multidimensional datasets across 543 constituencies, making it challenging to extract clear patterns on voter turnout, regional dominance, and swing trends.',
      'Designed and built an end-to-end interactive Business Intelligence report in Microsoft Power BI, engineering relational data models and custom DAX measures to calculate vote shares, victory margins, and demographic KPIs.',
      'Delivered nationwide party comparisons, state-level and constituency drill-downs, geospatial heatmaps, gender-based candidate performance metrics, and historical trend comparisons.',
    ],
  },
  {
    id: 'movie-recommender',
    title: 'CineMatch — ML Movie Recommender System',
    img: '/projects/movie-recommender/cover.png',
    link: '/projects/movie-recommender',
    date: 'July 2025',
    liveLink: "https://movie-recommendor-system-abhay.streamlit.app/",
    company: 'Machine Learning Personal Project',
    primary: '#1f3a34',
    accentColor: '#f0f4f1',
    secondary: '#F4F7F5',
    fillColor: '#e1f2ea',
    menuColor: '#2f8a6a',
    menuFontColor: '#f0f4f1',
    images: [
      { src: '/projects/movie-recommender/1.png', tag: 'big', isRight: false },
      { src: '/projects/movie-recommender/2.png', tag: 'small', isRight: false },
      { src: '/projects/movie-recommender/3.png', tag: 'small', isRight: true },
    ],
    desc: [
      'With thousands of titles on streaming platforms, users face choice fatigue finding movies that align with their specific taste in genres, cast, and storyline.',
      'Engineered a content-based recommendation engine in Python using Scikit-Learn, Pandas, and NumPy. Vectorized movie metadata (genres, cast, keywords, crew) via TF-IDF and computed high-dimensional Cosine Similarity matrices.',
      'Integrated The Movie Database (TMDB) API to fetch dynamic high-resolution movie posters and metadata, deploying an interactive web application on Streamlit with cached vector computation for real-time recommendations.',
    ],
  },
];
export default projects;
